
###
http://localhost:8080/api/v1/auth

###
POST http://localhost:8080/api/v1/auth/resgiter
Content-Type: application/json

{
    "username": "John Doe",
    "password": "passwords"
}

###
http://localhost:8080/api/v1

###
http://localhost:8080/api/v1/app

###
http://localhost:8080/api/v1/app/profile

###
http://localhost:8080/api/v1/app/events/1/attendees

###
http://localhost:8080/api/v1/user/23

###
http://localhost:8080/todos/23


### 
http://localhost:8080/public/test.pdf

###
http://localhost:8080/api/v1/tweets

###
http://localhost:8080/api/v1/hello

###
http://localhost:8080/api/v1/hello2

###
http://localhost:8080/api/v1/users

###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "name": "John",
    "age": 30,
    "email": "john@example.com"
}

// Set Bearer token in Authorization header
###
GET http://localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNjg0NjQzMzU2LCJleHAiOjE2ODQ2NDMzNjZ9.1z83d338383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383


###
GET http://localhost:8080/delay

###
POST http://localhost:8080/send-email


###
GET http://localhost:8080/api/v1/home


###
HEAD http://localhost:8080/api/v1/head-test

###
TRACE http://localhost:8080/api/v1/trace-test

###
OPTIONS http://localhost:8080/api/v1/options-test

###
PATCH http://localhost:8080/api/v1/patch-test

###
GET http://localhost:8080/not-found

###
GET http://localhost:8080/api/v1/fastify

###
GET http://localhost:8080/api/v1/api/fastify2

###
GET http://localhost:8080/api/v1/new-routes/new

###
POST http://localhost:8080/api/v1/new-routes/new

###
GET http://localhost:8080/api/v1/app/product/1

###

GET http://localhost:8080/api/v1/all

###

POST http://localhost:8080/api/v1/all

###

GET http://localhost:8080/api/v1/author/John/post/1

###

GET http://localhost:8080/api/v1/wildcard/test/codigo

###

POST http://localhost:8080/api/v1/parsed
Content-Type: application/json

{
    "text": "My Post",
    "isLiked": true
}

###

POST http://localhost:8080/api/v1/blob
Content-Type: application/json

{
    "name": "Body to blob",
}

###

POST http://localhost:8080/api/v1/array-buffer
Content-Type: application/json

{
    "name": "Body to blob",
}

###

POST http://localhost:8080/api/v1/form-data
Content-Disposition: form-data; name="description"

All text of description.

###
GET http://localhost:8080/api/v1/books