
###
http://localhost:3000/user/23


### 
http://localhost:3000/index.html

###
http://localhost:3000/tweets

###
http://localhost:3000/hello

###
http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John",
    "age": 30,
    "email": "john@example.com"
}