
###
http://localhost:3000/auth

###
http://localhost:3000/auth/resgiter

###
http://localhost:3000/app

###
http://localhost:3000/app/profile

###
http://localhost:3000/user/23

###
http://localhost:3000/todos/23


### 
http://localhost:3000/public/test.pdf

###
http://localhost:3000/tweets

###
http://localhost:3000/hello

###
http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John",
    "age": 30,
    "email": "john@example.com"
}

// Set Bearer token in Authorization header
###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNjg0NjQzMzU2LCJleHAiOjE2ODQ2NDMzNjZ9.1z83d338383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383838383


###
GET http://localhost:3000/delay

###
POST http://localhost:3000/send-email