/// Generates a **typed Dart API client** from an OpenAPI 3.1 document (such as
/// the one produced by [OpenApi.toJson]).
///
/// For each operation it emits a typed method; object request bodies and 2xx
/// response bodies become model classes with `fromJson` / `toJson`. The
/// generated client uses `dart:io` `HttpClient` only — no external dependency.
///
/// ```dart
/// final source = generateDartClient(api.toJson(), baseUrl: 'https://api.example.com');
/// File('lib/api_client.dart').writeAsStringSync(source);
/// ```
String generateDartClient(
  Map<String, dynamic> spec, {
  String className = 'ApiClient',
  String baseUrl = 'http://localhost:3000',
}) {
  final models = <String, String>{};
  final methods = <String>[];

  final paths = (spec['paths'] as Map?) ?? const {};
  paths.forEach((path, item) {
    if (item is! Map) return;
    item.forEach((method, op) {
      if (op is! Map || !_httpMethods.contains(method.toString().toLowerCase())) {
        return;
      }
      final opName = _opName(method.toString(), path.toString(), op);

      var bodyType = '';
      final reqSchema = _bodySchema(op['requestBody']);
      if (_isObject(reqSchema)) {
        final name = '${_pascal(opName)}Request';
        models[name] = _model(name, reqSchema!);
        bodyType = name;
      }

      var respType = 'void';
      final resSchema = _responseSchema(op['responses']);
      if (_isObject(resSchema)) {
        final name = '${_pascal(opName)}Response';
        models[name] = _model(name, resSchema!);
        respType = name;
      }

      methods.add(_method(opName, method.toString(), path.toString(), op,
          bodyType, respType));
    });
  });

  final b = StringBuffer();
  b.writeln('// GENERATED by darto_openapi — do not edit by hand.');
  b.writeln("import 'dart:convert';");
  b.writeln("import 'dart:io';");
  b.writeln();
  for (final m in models.values) {
    b.writeln(m);
    b.writeln();
  }
  b.writeln('class $className {');
  b.writeln('  final String baseUrl;');
  b.writeln('  final HttpClient _http = HttpClient();');
  b.writeln('  $className({this.baseUrl = ${_q(baseUrl)}});');
  b.writeln('  void close() => _http.close(force: true);');
  b.writeln();
  for (final m in methods) {
    b.writeln(m);
    b.writeln();
  }
  b.writeln(_sendMethod);
  b.writeln('}');
  b.writeln();
  b.writeln(_apiException);
  return b.toString();
}

const _httpMethods = {'get', 'post', 'put', 'patch', 'delete', 'head', 'options'};

Map<String, dynamic>? _bodySchema(Object? requestBody) {
  if (requestBody is! Map) return null;
  final content = requestBody['content'];
  if (content is! Map) return null;
  final json = content['application/json'];
  if (json is! Map) return null;
  return (json['schema'] as Map?)?.cast<String, dynamic>();
}

Map<String, dynamic>? _responseSchema(Object? responses) {
  if (responses is! Map) return null;
  for (final code in const ['200', '201']) {
    final r = responses[code];
    if (r is! Map) continue;
    final content = r['content'];
    if (content is! Map) continue;
    final json = content['application/json'];
    if (json is Map && json['schema'] is Map) {
      return (json['schema'] as Map).cast<String, dynamic>();
    }
  }
  return null;
}

bool _isObject(Map<String, dynamic>? s) => s != null && s['type'] == 'object';

String _model(String name, Map<String, dynamic> schema) {
  final props = (schema['properties'] as Map?) ?? const {};
  final required =
      ((schema['required'] as List?) ?? const []).map((e) => '$e').toSet();

  final fields = <_Field>[];
  props.forEach((k, v) {
    fields.add(_Field(
      '$k',
      _dartType((v as Map?)?.cast<String, dynamic>()),
      required.contains('$k'),
    ));
  });

  final b = StringBuffer();
  b.writeln('class $name {');
  for (final f in fields) {
    b.writeln('  final ${f.type}${f.required ? '' : '?'} ${_camel(f.name)};');
  }
  b.writeln(
      '  $name({${fields.map((f) => '${f.required ? 'required ' : ''}this.${_camel(f.name)}').join(', ')}});');
  b.writeln(
      '  factory $name.fromJson(Map<String, dynamic> json) => $name(');
  for (final f in fields) {
    b.writeln('        ${_camel(f.name)}: ${_fromJson(f)},');
  }
  b.writeln('      );');
  b.writeln('  Map<String, dynamic> toJson() => {');
  for (final f in fields) {
    if (f.required) {
      b.writeln('        ${_q(f.name)}: ${_camel(f.name)},');
    } else {
      b.writeln(
          '        if (${_camel(f.name)} != null) ${_q(f.name)}: ${_camel(f.name)},');
    }
  }
  b.writeln('      };');
  b.writeln('}');
  return b.toString();
}

String _fromJson(_Field f) {
  final key = "json[${_q(f.name)}]";
  if (f.type.startsWith('List<')) {
    final inner = f.type.substring(5, f.type.length - 1);
    return f.required
        ? '($key as List).cast<$inner>()'
        : '($key as List?)?.cast<$inner>()';
  }
  return f.required ? '$key as ${f.type}' : '$key as ${f.type}?';
}

String _method(String opName, String method, String path, Map op,
    String bodyType, String respType) {
  final params = ((op['parameters'] as List?) ?? const []).whereType<Map>();
  final pathParams = params.where((p) => p['in'] == 'path').toList();
  final queryParams = params.where((p) => p['in'] == 'query').toList();

  final positional = <String>[
    for (final p in pathParams)
      '${_dartType((p['schema'] as Map?)?.cast<String, dynamic>())} ${_camel('${p['name']}')}',
    if (bodyType.isNotEmpty) '$bodyType body',
  ];
  final named = [
    for (final q in queryParams)
      '${_dartType((q['schema'] as Map?)?.cast<String, dynamic>())}? ${_camel('${q['name']}')}',
  ];
  final sig = [...positional, if (named.isNotEmpty) '{${named.join(', ')}}'].join(', ');

  var url = path;
  for (final p in pathParams) {
    url = url.replaceAll('{${p['name']}}', '\${${_camel('${p['name']}')}}');
  }

  final ret = respType == 'void' ? 'Future<void>' : 'Future<$respType>';
  final b = StringBuffer();
  b.writeln('  $ret $opName($sig) async {');
  if (queryParams.isNotEmpty) {
    b.writeln('    final query = <String, String>{');
    for (final q in queryParams) {
      final n = _camel('${q['name']}');
      b.writeln('      if ($n != null) ${_q('${q['name']}')}: \'\$$n\',');
    }
    b.writeln('    };');
  }
  final args = StringBuffer("${_q(method.toUpperCase())}, '$url'");
  if (bodyType.isNotEmpty) args.write(', body: body.toJson()');
  if (queryParams.isNotEmpty) args.write(', query: query');
  if (respType == 'void') {
    b.writeln('    await _send($args);');
  } else {
    b.writeln('    final json = await _send($args);');
    b.writeln('    return $respType.fromJson(json);');
  }
  b.writeln('  }');
  return b.toString();
}

const _sendMethod = '''
  Future<Map<String, dynamic>> _send(
    String method,
    String path, {
    Map<String, dynamic>? body,
    Map<String, String>? query,
  }) async {
    var uri = Uri.parse('\$baseUrl\$path');
    if (query != null && query.isNotEmpty) uri = uri.replace(queryParameters: query);
    final req = await _http.openUrl(method, uri);
    if (body != null) {
      req.headers.contentType = ContentType.json;
      req.write(jsonEncode(body));
    }
    final res = await req.close();
    final text = await res.transform(utf8.decoder).join();
    if (res.statusCode >= 400) throw ApiException(res.statusCode, text);
    return text.isEmpty ? <String, dynamic>{} : jsonDecode(text) as Map<String, dynamic>;
  }''';

const _apiException = '''
class ApiException implements Exception {
  final int statusCode;
  final String body;
  ApiException(this.statusCode, this.body);
  @override
  String toString() => 'ApiException(\$statusCode): \$body';
}''';

String _opName(String method, String path, Map op) {
  final opId = op['operationId'];
  if (opId is String && opId.isNotEmpty) return _camel(opId);
  final b = StringBuffer(method.toLowerCase());
  for (final seg in path.split('/')) {
    if (seg.isEmpty) continue;
    if (seg.startsWith('{') && seg.endsWith('}')) {
      b.write('By${_pascal(seg.substring(1, seg.length - 1))}');
    } else {
      b.write(_pascal(seg));
    }
  }
  return b.toString();
}

String _dartType(Map<String, dynamic>? s) {
  if (s == null) return 'dynamic';
  final t = s['type'];
  final type = t is List
      ? (t.map((e) => '$e').firstWhere((x) => x != 'null', orElse: () => ''))
      : (t is String ? t : '');
  switch (type) {
    case 'string':
      return 'String';
    case 'integer':
      return 'int';
    case 'number':
      return 'double';
    case 'boolean':
      return 'bool';
    case 'array':
      return 'List<${_dartType((s['items'] as Map?)?.cast<String, dynamic>())}>';
    case 'object':
      return 'Map<String, dynamic>';
    default:
      return 'dynamic';
  }
}

String _pascal(String s) {
  final parts = s.split(RegExp(r'[^A-Za-z0-9]+')).where((p) => p.isNotEmpty);
  return parts.map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

String _camel(String s) {
  final p = _pascal(s);
  return p.isEmpty ? p : p[0].toLowerCase() + p.substring(1);
}

String _q(String s) => "'${s.replaceAll(r'$', r'\$').replaceAll("'", r"\'")}'";

class _Field {
  final String name;
  final String type;
  final bool required;
  _Field(this.name, this.type, this.required);
}
