name: darto_view
description: Template engine plugin for Darto. Configures views path and engine, enabling c.render() in route handlers.
version: 1.0.1
homepage: https://github.com/evandersondev/darto/tree/main/darto_view
repository: https://github.com/evandersondev/darto

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  darto: ^1.1.0
  mustache_template: ^2.0.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
