name: example_openapi
description: Darto — OpenAPI 3.1 spec + Scalar docs with darto_openapi
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  darto:
    path: ../../darto
  darto_openapi:
    path: ../../darto_openapi

dev_dependencies:
  lints: ^5.0.0

dependency_overrides:
  darto:
    path: ../../darto
