name: example_cache
description: Darto — caching with darto_cache (Memory + Redis)
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  darto:
    path: ../../darto
  darto_cache:
    path: ../../darto_cache

dev_dependencies:
  lints: ^5.0.0

dependency_overrides:
  darto:
    path: ../../darto
