name: example_websocket
description: Darto v2 — WebSocket server example
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  darto:
    path: ../../darto
  darto_ws:
    path: ../../darto_ws

dev_dependencies:
  lints: ^5.0.0
