import 'dart:convert';
import 'dart:io';

import 'package:darto/darto.dart' show RouteSpec;
import '../client_generator.dart';
import 'package:path/path.dart' as p;

/// `darto gen client flutter [--input lib/app.dart]`
///
/// Runs a temporary Dart script inside the user's project to extract routes
/// from `createApp()` at runtime, then generates a fully typed client.
Future<void> runGenClient(List<String> args) async {
  final platform = args.isNotEmpty ? args[0].toLowerCase() : 'flutter';

  if (platform != 'flutter' && platform != 'dart') {
    _err('Unknown platform "$platform". Use: flutter | dart');
  }

  final outPath =
      _flag(args, '--output') ?? _flag(args, '-o') ?? p.join('lib', 'api_client.dart');
  final baseUrl =
      _flag(args, '--base-url') ?? _flag(args, '-b') ?? 'http://localhost:3000';
  final className = _flag(args, '--class') ?? 'ApiClient';
  final inputFile =
      _flag(args, '--input') ?? _flag(args, '-i') ?? 'lib/app.dart';

  // ── Validate input file ────────────────────────────────────────────────────
  if (!File(inputFile).existsSync()) {
    _err(
      'Input file not found: $inputFile\n'
      '  Make sure lib/app.dart exists and exports createApp(),\n'
      '  or pass --input <path> pointing to a file that exports createApp().',
    );
  }

  // ── Read package name from pubspec.yaml ────────────────────────────────────
  final packageName = _readPackageName();
  if (packageName == null) {
    _err('Could not read pubspec.yaml. Run `darto gen client` from the project root.');
  }

  // ── Build package import for the input file ────────────────────────────────
  // Only lib/ files can be imported via package: URI.
  final String importLine;
  if (inputFile.startsWith('lib/') || inputFile.startsWith('lib\\')) {
    final relToLib = inputFile.replaceFirst(RegExp(r'^lib[/\\]'), '');
    importLine = "import 'package:$packageName/$relToLib';";
  } else {
    // For files outside lib/ (e.g. bin/server.dart) use a relative import
    // from bin/ where the temp script will live.
    final rel = p.relative(inputFile, from: 'bin');
    importLine = "import '$rel';";
  }

  // ── Write extraction script ────────────────────────────────────────────────
  const tempScript = 'bin/_darto_extract_routes.dart';
  File(tempScript).writeAsStringSync('''
// AUTO-GENERATED by darto_cli — safe to delete
// ignore_for_file: depend_on_referenced_packages
import 'dart:convert';
import 'dart:io';
$importLine

void main() {
  final app = createApp();
  final data = app.routes
      .map((r) => {'method': r.method, 'path': r.path})
      .toList();
  stdout.write(jsonEncode(data));
}
''');

  // ── Run extraction script ──────────────────────────────────────────────────
  stdout.writeln('\x1B[90mExtracting routes from $inputFile...\x1B[0m');

  final result = await Process.run(
    'dart',
    ['run', tempScript],
    runInShell: true,
  );

  // Always clean up
  try {
    File(tempScript).deleteSync();
  } catch (_) {}

  if (result.exitCode != 0) {
    stderr.writeln('\x1B[31m[ERROR] Failed to extract routes:\x1B[0m');
    stderr.writeln(result.stderr.toString().trim());
    exit(result.exitCode);
  }

  // ── Parse routes ───────────────────────────────────────────────────────────
  final List<RouteSpec> routes;
  try {
    final raw = jsonDecode(result.stdout as String) as List<dynamic>;
    routes = raw
        .cast<Map<String, dynamic>>()
        .map((r) => RouteSpec(method: r['method'] as String, path: r['path'] as String))
        .toList();
  } catch (e) {
    _err('Could not parse routes output. Ensure createApp() returns a Darto instance.\n  $e');
  }

  if (routes.isEmpty) {
    stderr.writeln('\x1B[33m[WARN] No routes found in the app. '
        'Make sure routes are registered before generate runs.\x1B[0m');
  }

  // ── Generate client ────────────────────────────────────────────────────────
  final gen = ClientGenerator(routes);
  final code = gen.generate(className: className, baseUrl: baseUrl);

  final outFile = File(outPath);
  outFile.parent.createSync(recursive: true);
  outFile.writeAsStringSync(code);

  stdout.writeln('\x1B[32m✓  Generated ${routes.length} route(s) → ${p.relative(outPath)}\x1B[0m');

  // ── Ensure `http` package is available ────────────────────────────────────
  if (!_hasDependency('http')) {
    stdout.writeln('\x1B[90mAdding missing dependency: http...\x1B[0m');
    final addResult = await Process.run(
      'dart',
      ['pub', 'add', 'http'],
      runInShell: true,
    );
    if (addResult.exitCode == 0) {
      stdout.writeln('\x1B[32m✓  http added to pubspec.yaml\x1B[0m');
    } else {
      stdout.writeln(
        '\x1B[33m[WARN] Could not add http automatically.\x1B[0m\n'
        '\x1B[36m       Run manually: dart pub add http\x1B[0m',
      );
    }
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

String? _readPackageName() {
  try {
    final lines = File('pubspec.yaml').readAsLinesSync();
    for (final line in lines) {
      final trimmed = line.trim();
      if (trimmed.startsWith('name:')) {
        return trimmed.replaceFirst('name:', '').trim();
      }
    }
  } catch (_) {}
  return null;
}

bool _hasDependency(String name) {
  try {
    final content = File('pubspec.yaml').readAsStringSync();
    return RegExp(r'^\s+' + name + r'\s*:', multiLine: true).hasMatch(content);
  } catch (_) {
    return false;
  }
}

String? _flag(List<String> args, String flag) {
  final idx = args.indexOf(flag);
  if (idx == -1 || idx + 1 >= args.length) return null;
  return args[idx + 1];
}

Never _err(String msg) {
  stderr.writeln('\x1B[31m[ERROR] $msg\x1B[0m');
  exit(1);
}
