import 'package:darto/darto.dart';

/// Generates a modular, typed Dart/Flutter API client from [RouteSpec]s.
///
/// Routes are grouped by their first path segment (module). Each module
/// becomes its own class, exposed as a field on the root client:
///
/// ```dart
/// final api = ApiClient(baseUrl: 'http://localhost:3000');
/// api.setToken(token);
///
/// final tweets = await api.tweets.getAll();
/// final user   = await api.users.getById('42');
/// await api.auth.login({'email': '...', 'password': '...'});
/// ```
///
/// Usage:
/// ```dart
/// final gen = ClientGenerator(app.routes);
/// final code = gen.generate();
/// File('lib/api_client.dart').writeAsStringSync(code);
/// ```
class ClientGenerator {
  final List<RouteSpec> routes;

  ClientGenerator(this.routes);

  /// Returns the full generated Dart source as a [String].
  String generate({
    String className = 'ApiClient',
    String baseUrl = 'http://localhost:3000',
  }) {
    // Group routes by module (first non-empty, non-param path segment)
    final modules = <String, List<RouteSpec>>{};
    final rootRoutes = <RouteSpec>[];
    for (final r in routes) {
      final mod = _moduleOf(r.path);
      if (mod == null) {
        rootRoutes.add(r);
      } else {
        (modules[mod] ??= []).add(r);
      }
    }

    final buf = StringBuffer();

    buf.writeln('// GENERATED BY darto_client_generator — DO NOT EDIT');
    buf.writeln('// Run: darto gen client flutter');
    buf.writeln();
    buf.writeln("import 'dart:convert';");
    buf.writeln("import 'package:http/http.dart' as http;");
    buf.writeln();

    // ── Root client class ────────────────────────────────────────────────────
    buf.writeln('class $className {');
    buf.writeln('  final String baseUrl;');
    buf.writeln('  String? _token;');
    buf.writeln();

    for (final mod in modules.keys) {
      buf.writeln('  late final ${_cap(mod)}Module $mod;');
    }
    if (modules.isNotEmpty) buf.writeln();

    buf.writeln('  $className({this.baseUrl = ${_q(baseUrl)}}) {');
    for (final mod in modules.keys) {
      buf.writeln('    $mod = ${_cap(mod)}Module(this);');
    }
    buf.writeln('  }');
    buf.writeln();

    buf.writeln('  void setToken(String token) => _token = token;');
    buf.writeln('  void clearToken() => _token = null;');
    buf.writeln();

    buf.writeln('  Map<String, String> get _headers => {');
    buf.writeln("    'Content-Type': 'application/json',");
    buf.writeln("    if (_token != null) 'Authorization': 'Bearer \$_token',");
    buf.writeln('  };');
    buf.writeln();

    _writeCoreRequest(buf);

    for (final r in rootRoutes) {
      _writeMethod(buf, r, caller: '_request', indent: 2);
    }

    buf.writeln('}');
    buf.writeln();

    // ── ApiException ─────────────────────────────────────────────────────────
    buf.writeln('class ApiException implements Exception {');
    buf.writeln('  final int statusCode;');
    buf.writeln('  final String body;');
    buf.writeln('  const ApiException(this.statusCode, this.body);');
    buf.writeln('  @override');
    buf.writeln("  String toString() => 'ApiException(\$statusCode): \$body';");
    buf.writeln('}');
    buf.writeln();

    // ── Module classes ────────────────────────────────────────────────────────
    for (final entry in modules.entries) {
      final mod = entry.key;
      buf.writeln('class ${_cap(mod)}Module {');
      buf.writeln('  final $className _c;');
      buf.writeln('  ${_cap(mod)}Module(this._c);');
      buf.writeln();
      for (final r in entry.value) {
        _writeMethod(buf, r, caller: '_c._request', indent: 2,
            stripPrefix: '/$mod');
      }
      buf.writeln('}');
      buf.writeln();
    }

    return buf.toString();
  }

  // ── Code generation helpers ───────────────────────────────────────────────

  void _writeCoreRequest(StringBuffer buf) {
    buf.writeln('  Future<dynamic> _request(');
    buf.writeln('    String method,');
    buf.writeln('    String path, {');
    buf.writeln('    Map<String, dynamic>? body,');
    buf.writeln('    Map<String, String>? query,');
    buf.writeln('  }) async {');
    buf.writeln("    var uri = Uri.parse('\$baseUrl\$path');");
    buf.writeln('    if (query != null && query.isNotEmpty) {');
    buf.writeln('      uri = uri.replace(queryParameters: query);');
    buf.writeln('    }');
    buf.writeln('    final encoded = body != null ? jsonEncode(body) : null;');
    buf.writeln('    final http.Response res;');
    buf.writeln('    switch (method) {');
    buf.writeln("      case 'GET':    res = await http.get(uri, headers: _headers);");
    buf.writeln("      case 'POST':   res = await http.post(uri, headers: _headers, body: encoded);");
    buf.writeln("      case 'PUT':    res = await http.put(uri, headers: _headers, body: encoded);");
    buf.writeln("      case 'PATCH':  res = await http.patch(uri, headers: _headers, body: encoded);");
    buf.writeln("      case 'DELETE': res = await http.delete(uri, headers: _headers);");
    buf.writeln("      default:       throw UnsupportedError('Unsupported: \$method');");
    buf.writeln('    }');
    buf.writeln('    if (res.statusCode >= 400) {');
    buf.writeln('      throw ApiException(res.statusCode, res.body);');
    buf.writeln('    }');
    buf.writeln('    if (res.body.isEmpty) return null;');
    buf.writeln('    return jsonDecode(res.body);');
    buf.writeln('  }');
    buf.writeln();
  }

  void _writeMethod(
    StringBuffer buf,
    RouteSpec route, {
    required String caller,
    required int indent,
    String? stripPrefix,
  }) {
    final pad = ' ' * indent;
    final method = route.method.toUpperCase();
    final path = route.path;
    final params = _extractParams(path);
    final hasBody = const {'POST', 'PUT', 'PATCH'}.contains(method);
    final isGet = method == 'GET';

    final name = _methodName(method, path, stripPrefix: stripPrefix);

    final positional = params.map((p) => 'String $p').toList();
    final named = [
      if (hasBody) 'Map<String, dynamic>? body',
      if (isGet) 'Map<String, String>? query',
    ];

    var interpolated = path;
    for (final p in params) {
      interpolated = interpolated.replaceFirst(':$p', '\$$p');
    }
    // Remove trailing slash
    if (interpolated.length > 1 && interpolated.endsWith('/')) {
      interpolated = interpolated.substring(0, interpolated.length - 1);
    }

    final bodyArg = hasBody ? ', body: body' : '';
    final queryArg = isGet ? ', query: query' : '';

    if (named.isEmpty) {
      final argList = positional.join(', ');
      buf.writeln('${pad}Future<dynamic> $name($argList) =>');
      buf.writeln("$pad    $caller('$method', '$interpolated'$bodyArg$queryArg);");
    } else if (positional.isEmpty) {
      final namedList = named.join(', ');
      buf.writeln('${pad}Future<dynamic> $name({$namedList}) =>');
      buf.writeln("$pad    $caller('$method', '$interpolated'$bodyArg$queryArg);");
    } else {
      final posList = positional.join(', ');
      final namedList = named.join(', ');
      buf.writeln('${pad}Future<dynamic> $name($posList, {$namedList}) =>');
      buf.writeln("$pad    $caller('$method', '$interpolated'$bodyArg$queryArg);");
    }
    buf.writeln();
  }

  // ── Path analysis ─────────────────────────────────────────────────────────

  String? _moduleOf(String path) {
    final segs = path.split('/').where((s) => s.isNotEmpty).toList();
    if (segs.isEmpty) return null;
    return segs.first.startsWith(':') ? null : segs.first;
  }

  /// Derives a clean method name from HTTP verb + path.
  ///
  /// GET  /users          → getAll
  /// GET  /users/:id      → getById
  /// POST /users          → create
  /// PUT  /users/:id      → update
  /// DELETE /users/:id    → delete
  /// POST /auth/login     → login
  /// GET  /auth/me        → me
  String _methodName(String method, String path, {String? stripPrefix}) {
    var rel = stripPrefix != null ? path.replaceFirst(stripPrefix, '') : path;
    rel = rel.replaceAll(RegExp(r'^/+'), '');

    final segs = rel.split('/').where((s) => s.isNotEmpty).toList();
    final named = segs.where((s) => !s.startsWith(':')).toList();
    final hasParam = segs.any((s) => s.startsWith(':'));

    if (named.isEmpty) {
      switch (method) {
        case 'GET':
          return hasParam ? 'getById' : 'getAll';
        case 'POST':
          return 'create';
        case 'PUT':
        case 'PATCH':
          return hasParam ? 'update' : method.toLowerCase();
        case 'DELETE':
          return hasParam ? 'delete' : 'deleteAll';
      }
    }

    final last = named.last;
    switch (method) {
      case 'GET':
        return hasParam ? 'get${_cap(last)}' : _lcFirst(last);
      case 'POST':
        return _lcFirst(last);
      case 'PUT':
      case 'PATCH':
        return 'update${_cap(last)}';
      case 'DELETE':
        return 'delete${_cap(last)}';
    }
    return '${method.toLowerCase()}${_cap(last)}';
  }

  List<String> _extractParams(String path) =>
      RegExp(r':(\w+)\??').allMatches(path).map((m) => m.group(1)!).toList();

  String _cap(String s) =>
      s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);

  String _lcFirst(String s) =>
      s.isEmpty ? s : s[0].toLowerCase() + s.substring(1);

  String _q(String s) => "'$s'";
}
